pipeline {
    agent any

    stages {
        stage('checkout'){
            steps {
                git url: 'https://github.com/vanxuanty95/surf_be.git'
            }
        }
        stage('go build'){
            steps {
                sh 'docker run -i --rm -v $PWD:/go/src/surf_be/ -w /go/src/surf_be golang:1.16-alpine go build -mod vendor -v -o surf_be.bin .'
            }
        }
        stage('docker build'){
            steps {
                sh 'docker build -f deployment/dev/Dockerfile .'
            }
        }
        stage('deploy'){
            steps{
                sh './deployment/dev/deploy.sh'
            }
        }
    }
}