pipeline {
    agent any

    stages {
        stage('checkout'){
            steps {
                git url: 'https://github.com/vanxuanty95/surf_be.git'
            }
        }
        stage('go build'){
            steps {
                sh 'docker run -i --rm -v $PWD:/go/src/surf_be/ -w /go/src/surf_be golang:1.16-alpine go build -mod vendor -v -o surf_be.bin .'
            }
        }
        stage('docker build'){
            steps {
                sh 'ssh host.docker.internal ''docker cp 0bcda5f31e67:/var/jenkins_home/workspace/surf/surf_be/surf_be.bin /host/surf_be.bin'
                sh 'docker build -f deployment/dev/Dockerfile .'
            }
        }
        stage('deploy'){
            steps{
                sh 'ssh host.docker.internal'
            }
        }
    }
}