server:
  pfit_mgmt:
    api_port: 8082
  binance:
    websocket:
      ws_url: "wss://stream.binance.com/ws"
      stream_url: "wss://testnet.binance.vision/stream"
      limitRequest: 100
    restful:
      url: "https://testnet.binance.vision"
  database:
    redis:
      host: "172.17.0.1"
      port: 6379
      password: "Passw0rd998"