server:
  pfit_mgmt:
    api_port: 8082
  binance:
    websocket:
      ws_url: "wss://testnet.binance.vision/ws"
      stream_url: "wss://testnet.binance.vision/stream"
      limitRequest: 100
    restful:
      url: "https://testnet.binance.vision/api"
  database:
    redis:
      host: localhost