server:
  pfit_mgmt:
    api_port: 8082
  binance:
    websocket:
      ws_url: "wss://stream.binance.com/ws"
      stream_url: "wss://testnet.binance.vision/stream"
      limitRequest: 100
    restful:
      url: "https://testnet.binance.vision"
  database:
    redis:
      host: "vanxuanty.ddns.net"
      port: 6379
      password: "Passw0rd998"
    mongo:
      host:
        - "vanxuanty.ddns.net"
      port: 27017
      auth_database: admin
      username: "admin"
      password: "P@ssw0rd"
      database: "local-surf-be"
      collection:
        bot: "bot"
        transaction: "transaction"